spring:
  profiles.active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

logging:
  level:
    org.springframework.jdbc: debug
    hello.itemservice.repository.mybatis: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
#  mapper-locations: classpath:mapper/**/*.xml
